FROM alpine:latest

RUN apk add git gcc g++ cmake make --no-cache

WORKDIR /usr/src/

ENV cc=gcc
ENV cxx=g++

# Clone Repo
RUN ["git", "clone", "https://github.com/Podrum/Podrum.git", "Podrum"]
WORKDIR /usr/src/Podrum

# Cmake
RUN ["cmake", "."]
RUN ["make"]

# Setup Entrypoint
COPY ./start.sh /usr/src/Podrum/start.sh
ENTRYPOINT ["sh", "./start.sh"]