services:
  redis:
    image: redis:alpine
    containerName: redis
    command: ["redis-server", "--save", 60, 1, "--loglevel", "warning"]  # Saves if there's atleast 1 write, occurs every 60s
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always